// generated by stringer -output model/model_string.go -type AccountStatus,MigrationAccountStatus,SpedizioneStatus,SpedizioneEsito model; DO NOT EDIT

package model

import "fmt"

const _AccountStatus_name = "AccountAttivoAccountSospeso"

var _AccountStatus_index = [...]uint8{0, 13, 27}

func (i AccountStatus) String() string {
	if i < 0 || i >= AccountStatus(len(_AccountStatus_index)-1) {
		return fmt.Sprintf("AccountStatus(%d)", i)
	}
	return _AccountStatus_name[_AccountStatus_index[i]:_AccountStatus_index[i+1]]
}

const _MigrationAccountStatus_name = "MigrAccDaSpedireMigrAccInCorsoMigrAccTerminata"

var _MigrationAccountStatus_index = [...]uint8{0, 16, 30, 46}

func (i MigrationAccountStatus) String() string {
	if i < 0 || i >= MigrationAccountStatus(len(_MigrationAccountStatus_index)-1) {
		return fmt.Sprintf("MigrationAccountStatus(%d)", i)
	}
	return _MigrationAccountStatus_name[_MigrationAccountStatus_index[i]:_MigrationAccountStatus_index[i+1]]
}

const _SpedizioneStatus_name = "SpedizioneCreataSpedizioneDaInviareSpedizioneInCorsoSpedizioneConsegnataSpedizioneErrore"

var _SpedizioneStatus_index = [...]uint8{0, 16, 35, 52, 72, 88}

func (i SpedizioneStatus) String() string {
	if i < 0 || i >= SpedizioneStatus(len(_SpedizioneStatus_index)-1) {
		return fmt.Sprintf("SpedizioneStatus(%d)", i)
	}
	return _SpedizioneStatus_name[_SpedizioneStatus_index[i]:_SpedizioneStatus_index[i+1]]
}

const _SpedizioneEsito_name = "EsitoNonDisponibileConsegnaOKErrConsegnaInGiacenzaErrConsegnaIndirizzoNonTrovatoErrConsegnaGenericoErrValidazione"

var _SpedizioneEsito_index = [...]uint8{0, 19, 29, 50, 80, 99, 113}

func (i SpedizioneEsito) String() string {
	i -= -1
	if i < 0 || i >= SpedizioneEsito(len(_SpedizioneEsito_index)-1) {
		return fmt.Sprintf("SpedizioneEsito(%d)", i+-1)
	}
	return _SpedizioneEsito_name[_SpedizioneEsito_index[i]:_SpedizioneEsito_index[i+1]]
}
